### ISSUE TITLE
Support Lemmy API v2

### ISSUE THREAD

**Issue by dessalines** [krawieck/lemmy_api_client#8]
So we're finalizing and readying the release of the v2 of the lemmy API within a week or two. I've updated `lemmy-js-client`,  which is what `lemmy-ui` uses, and you'll have to do a similar process for this dart client, and `lemmur`.

Here's the docs for the v2 API, which mostly link to the `lemmy-js-client`, which has the full typings:

https://github.com/LemmyNet/lemmy-docs/blob/main/src/en/contributing/websocket_http_api.md#data-types

The biggest differences you'll find are that the objects are much more hierarchical and normalized; rather than having a flat `PostView`, with things like `community_name` at the top level, you now have hierarchical objects:

```ts
export interface PostView {
    post: Post;
    creator: UserSafe;
    community: CommunitySafe;
    creator_banned_from_community: boolean;
    counts: PostAggregates;
    subscribed: boolean;
    saved: boolean;
    read: boolean;
    my_vote?: number;
}
```

All of these new types, forms, etc are linked in the docs above. Rather than find specific differences, it might be easier to just copy paste the typescript objects, then convert them to dart (I actually did this process going from rust -> typescript, to make sure everything matched exactly).

Let me know if there's anything I can do to help with this effort.

If you need an instance to test these with, https://enterprise.lemmy.ml and all the federation instances are using it.

cc @nutomic

**Comment by Nutomic** [comment]
It would also be good if you could review the new API first, and let us know if there is anything that should be changed. Its much easier to do changes now while it isnt released yet.

**Comment by shilangyu** [comment]
> I actually did this process going from rust -> typescript

That's exactly what I did when porting rust views to dart :)

I have a few remarks/questions:

1. What does it mean for `/v1`? Only bug fixes from now? (related to question 5.)
2. The js client seems to accept a `baseUrl` that is required to have the version path (ie. `https://lemmy.ml/api/v2`), but since the responses in `/v1` and `/v2` are different wouldn't it mean that passing a `baseUrl` equal to `https://lemmy.ml/api/v1` in `lemmy-js-client@v2` is wrong? Is there a reason why the version prefix is not appended by the client itself? (This may seem like a question not related to the dart client, but it will help me understand future plans)
3. Is there any clean way of checking whether an instance supports a given API version?
4. This will pose a pretty big challenge for lemmur since we are forced to support multiple API versions:
	1. Endpoints return differently formed responses, this means we would either have to normalize all API versions to some common models or have lemmur render a different view depending on the API version (something like `InstancePageV1`,`InstancePageV2` views). The first solution seems doable but bases on the assumption that they CAN be normalized. The later would be insanely tedious to maintain.
	2. Restricting certain actions/views based on the instance's API version
5. Will `/v2` enable functionality not available in `/v1`?

I had more questions in mind when I started writing this comment (5 hours ago, busy day) but forgot them in the meantime. Will let you know when I recall any of them.

**Comment by dessalines** [comment]
Sure thing.

> What does it mean for /v1? Only bug fixes from now? (related to question 5.)

v1 will essentially be dead in a few weeks, the prod servers won't be running it. I know the idea with these normally is that versions should alongside each other, but that wasn't doable here because of the massive DB and data structure changes involved.

> The js client seems to accept a baseUrl that is required to have the version path (ie. https://lemmy.ml/api/v2), but since the responses in /v1 and /v2 are different wouldn't it mean that passing a baseUrl equal to https://lemmy.ml/api/v1 in lemmy-js-client@v2 is wrong? Is there a reason why the version prefix is not appended by the client itself? (This may seem like a question not related to the dart client, but it will help me understand future plans)

Yeah with this js client I should probably be pre-pending the base url with the version in there, so that js clients don't have to do that themselves. I think lemmy-ui is the only user of it rn tho.

> Is there any clean way of checking whether an instance supports a given API version?

Not currently, other than using nodeinfo https://enterprise.lemmy.ml/nodeinfo/2.0.json , and making sure the version is > `v0.9.0`. I'll have to see if there's somewhere we could put an api version in the nodeinfo.

> This will pose a pretty big challenge for lemmur since we are forced to support multiple API versions: 

I highly recommend against doing this. In 1-2 weeks all lemmy servers will be on v2, and v1 should be effectively dead. I tried doing this with lemmy-ui at first, but the new hierarchical data structures would have made it much more of a hassle than its worth.

> Will /v2 enable functionality not available in /v1

No additional functionality yet besides the DB speeding up a lot, and making all the future DB changes like user and community blocks much simpler. You can check out that big PR / issue on lemmy for all the changes we've done w/ it. You'll also find as explained above that you'll be able to re-use objects like `post_view.community`, rather than have `post_view.community_name`, `post_view.community_actor_id`... etc.

**Comment by shilangyu** [comment]
> I highly recommend against doing this. In 1-2 weeks all lemmy servers will be on v2, and v1 should be effectively dead.

Well, if you're endorsing dropping v1 then I'm all for it.

Is it realistic for lemmur to only support instances running the latest API version? Is there a reason why an instance would hold off a lemmy upgrade? I'm trying to think how many instances will stop working on lemmur due to that.

**Comment by dessalines** [comment]
Ya, we're all for dropping v1. 

> Is it realistic for lemmur to only support instances running the latest API version?

Yes, servers that want to work with the newest lemmy-ui and lemmur versions will have to keep their servers up to date too. I can't think of any reason why a server would hold off on an update unless it breaks a lot or they dislike some of lemmy's design decisions. This isn't even as bad as when we might eventually have to add breaking changes to federation, which could potentially cut off some servers from each other. 

This upgrade process is gonna be very smooth tho, ppl will only have to change a version number in their docker-compose.yml files.
